const rawThemeTokens = [
  {
    key: 'clean-blue',
    name: 'Claro Azul',
    primary: '#1c8dff',
    secondary: '#0874e8',
    accent: '#20c7a8',
    background: '#f8fbff',
    surface: '#ffffff',
    surfaceAlt: '#fbfdff',
    border: '#e8f0f8',
    text: '#0b2346',
    textSoft: '#29415f',
    textMuted: '#607089',
    gradientFrom: '#f8fbff',
    gradientTo: '#eee6ff',
    glow: '0 22px 60px rgba(28, 141, 255, 0.24)',
    mode: 'Claro',
    verticals: ['dental', 'medical'],
    radius: '2rem',
    heroRadius: '2.25rem',
    cardStyle: 'glass',
    buttonStyle: 'glow',
    fontStyle: 'modern',
    sectionSpacing: 'py-24',
  },
  {
    key: 'warm-minimal',
    name: 'Claro Premium',
    primary: '#0f766e',
    secondary: '#115e59',
    accent: '#c084fc',
    background: '#fafaf7',
    surface: '#ffffff',
    surfaceAlt: '#f7faf8',
    border: '#e5ece8',
    text: '#10231f',
    textSoft: '#2e4841',
    textMuted: '#64736f',
    gradientFrom: '#fafaf7',
    gradientTo: '#f4eefd',
    glow: '0 22px 60px rgba(15, 118, 110, 0.22)',
    mode: 'Claro',
    verticals: ['aesthetic'],
    radius: '2rem',
    heroRadius: '2.5rem',
    cardStyle: 'luxury',
    buttonStyle: 'soft',
    fontStyle: 'premium',
    sectionSpacing: 'py-28',
  },
  {
    key: 'soft-lilac',
    name: 'Claro Lilás',
    primary: '#7657de',
    secondary: '#5b3ec8',
    accent: '#1c8dff',
    background: '#faf8ff',
    surface: '#ffffff',
    surfaceAlt: '#f8f4ff',
    border: '#ece5ff',
    text: '#201842',
    textSoft: '#4c416c',
    textMuted: '#6e6784',
    gradientFrom: '#faf8ff',
    gradientTo: '#e8f5ff',
    glow: '0 22px 60px rgba(118, 87, 222, 0.24)',
    mode: 'Claro',
    verticals: ['wellness', 'psychology'],
    radius: '2rem',
    heroRadius: '2.25rem',
    cardStyle: 'glass',
    buttonStyle: 'pill',
    fontStyle: 'calm',
    sectionSpacing: 'py-24',
  },
  {
    key: 'dark-slate',
    name: 'Escuro Grafite',
    primary: '#60a5fa',
    secondary: '#1e293b',
    accent: '#cbd5e1',
    background: '#06070a',
    surface: '#111827',
    surfaceAlt: '#0f172a',
    border: 'rgba(148, 163, 184, 0.22)',
    text: '#f4f4f5',
    textSoft: '#d7deea',
    textMuted: '#a7b4c8',
    gradientFrom: '#06070a',
    gradientTo: '#111827',
    glow: '0 24px 70px rgba(96, 165, 250, 0.22)',
    mode: 'Escuro',
    verticals: ['legal', 'consulting', 'finance'],
    radius: '1.4rem',
    heroRadius: '1.7rem',
    cardStyle: 'dark',
    buttonStyle: 'outline',
    fontStyle: 'corporate',
    sectionSpacing: 'py-24',
  },
  {
    key: 'dark-violet',
    name: 'Escuro Violeta',
    primary: '#a78bfa',
    secondary: '#7c3aed',
    accent: '#22d3ee',
    background: '#120c24',
    surface: '#24183f',
    surfaceAlt: '#211638',
    border: '#3a2a5e',
    text: '#fbf8ff',
    textSoft: '#dfd7f2',
    textMuted: '#c3b8dc',
    gradientFrom: '#120c24',
    gradientTo: '#0e7490',
    glow: '0 22px 60px rgba(167, 139, 250, 0.28)',
    mode: 'Escuro',
    verticals: ['technology', 'startup'],
    radius: '1.75rem',
    heroRadius: '2rem',
    cardStyle: 'glass-dark',
    buttonStyle: 'glow',
    fontStyle: 'tech',
    sectionSpacing: 'py-24',
  },
  {
    key: 'dark-emerald',
    name: 'Escuro Esmeralda',
    primary: '#2dd4bf',
    secondary: '#0f766e',
    accent: '#f59e0b',
    background: '#061a17',
    surface: '#10342f',
    surfaceAlt: '#0d2b27',
    border: '#1f4f48',
    text: '#f1fffc',
    textSoft: '#d3eee8',
    textMuted: '#a8c9c2',
    gradientFrom: '#061a17',
    gradientTo: '#78350f',
    glow: '0 22px 60px rgba(45, 212, 191, 0.22)',
    mode: 'Escuro',
    verticals: ['medical', 'wellness', 'fitness'],
    radius: '2rem',
    heroRadius: '2.25rem',
    cardStyle: 'solid',
    buttonStyle: 'glow',
    fontStyle: 'executive',
    sectionSpacing: 'py-24',
  },
  {
    key: 'minimal-white',
    name: 'Minimal White',
    primary: '#111827',
    secondary: '#6b7280',
    accent: '#2563eb',
    background: '#f7f7f5',
    surface: '#ffffff',
    surfaceAlt: '#f3f4f6',
    border: '#e5e7eb',
    text: '#0f172a',
    textSoft: '#475569',
    textMuted: '#94a3b8',
    gradientFrom: '#ffffff',
    gradientTo: '#f1f5f9',
    glow: 'rgba(37, 99, 235, 0.12)',
    mode: 'Claro',
    verticals: ['consulting', 'legal', 'realEstate'],
    radius: '1.25rem',
    heroRadius: '1.75rem',
    cardStyle: 'luxury',
    buttonStyle: 'outline',
    fontStyle: 'minimal',
    sectionSpacing: 'py-24',
  },
  {
    key: 'dark-luxury',
    name: 'Dark Luxury',
    primary: '#c9a96e',
    secondary: '#8b7355',
    accent: '#f5d08f',
    background: '#0a0a0a',
    surface: '#121212',
    surfaceAlt: '#1b1b1b',
    border: '#2a2a2a',
    text: '#f8f8f8',
    textSoft: '#d4d4d4',
    textMuted: '#8a8a8a',
    gradientFrom: '#1a1a1a',
    gradientTo: '#0a0a0a',
    glow: 'rgba(201, 169, 110, 0.18)',
    mode: 'Escuro',
    verticals: ['aesthetic', 'legal', 'realEstate'],
    radius: '1.65rem',
    heroRadius: '2rem',
    cardStyle: 'dark',
    buttonStyle: 'glow',
    fontStyle: 'luxury',
    sectionSpacing: 'py-28',
  },
  {
    key: 'editorial-black',
    name: 'Editorial Black',
    primary: '#ffffff',
    secondary: '#9ca3af',
    accent: '#8b5cf6',
    background: '#050505',
    surface: '#111111',
    surfaceAlt: '#191919',
    border: '#262626',
    text: '#fafafa',
    textSoft: '#d4d4d8',
    textMuted: '#71717a',
    gradientFrom: '#111111',
    gradientTo: '#050505',
    glow: 'rgba(139, 92, 246, 0.2)',
    mode: 'Escuro',
    verticals: ['technology', 'aesthetic', 'consulting'],
    radius: '1.1rem',
    heroRadius: '1.5rem',
    cardStyle: 'glass-dark',
    buttonStyle: 'outline',
    fontStyle: 'editorial',
    sectionSpacing: 'py-28',
  },
  {
    key: 'soft-medical',
    name: 'Soft Medical',
    primary: '#1d4ed8',
    secondary: '#60a5fa',
    accent: '#38bdf8',
    background: '#f6fbff',
    surface: '#ffffff',
    surfaceAlt: '#eef6ff',
    border: '#dbeafe',
    text: '#0f172a',
    textSoft: '#475569',
    textMuted: '#94a3b8',
    gradientFrom: '#ffffff',
    gradientTo: '#e0f2fe',
    glow: 'rgba(56, 189, 248, 0.18)',
    mode: 'Claro',
    verticals: ['medical', 'dental', 'wellness'],
    radius: '2rem',
    heroRadius: '2.25rem',
    cardStyle: 'glass',
    buttonStyle: 'glow',
    fontStyle: 'medical',
    sectionSpacing: 'py-24',
  },
  {
    key: 'gold-prestige',
    name: 'Gold Prestige',
    primary: '#d4af37',
    secondary: '#f5deb3',
    accent: '#ffd166',
    background: '#0f0c05',
    surface: '#1a1408',
    surfaceAlt: '#241b0d',
    border: '#3a2f18',
    text: '#fff8e7',
    textSoft: '#f3e9c9',
    textMuted: '#c2b280',
    gradientFrom: '#1f1708',
    gradientTo: '#0f0c05',
    glow: 'rgba(212, 175, 55, 0.22)',
    mode: 'Escuro',
    verticals: ['legal', 'aesthetic', 'realEstate'],
    radius: '1.75rem',
    heroRadius: '2.1rem',
    cardStyle: 'dark',
    buttonStyle: 'glow',
    fontStyle: 'prestige',
    sectionSpacing: 'py-28',
  },
  {
    key: 'neo-corporate',
    name: 'Neo Corporate',
    primary: '#6366f1',
    secondary: '#818cf8',
    accent: '#22d3ee',
    background: '#f5f7fb',
    surface: '#ffffff',
    surfaceAlt: '#eef2ff',
    border: '#dbe4ff',
    text: '#111827',
    textSoft: '#475569',
    textMuted: '#94a3b8',
    gradientFrom: '#6366f1',
    gradientTo: '#22d3ee',
    glow: 'rgba(99, 102, 241, 0.18)',
    mode: 'Claro',
    verticals: ['consulting', 'technology', 'finance'],
    radius: '1.5rem',
    heroRadius: '1.85rem',
    cardStyle: 'glass',
    buttonStyle: 'glow',
    fontStyle: 'corporate',
    sectionSpacing: 'py-24',
  },
  {
    key: 'creator-mode',
    name: 'Creator Mode',
    primary: '#ff4d6d',
    secondary: '#fb7185',
    accent: '#8b5cf6',
    background: '#fff8fb',
    surface: '#ffffff',
    surfaceAlt: '#ffe4ec',
    border: '#fecdd3',
    text: '#1e293b',
    textSoft: '#475569',
    textMuted: '#94a3b8',
    gradientFrom: '#ff4d6d',
    gradientTo: '#8b5cf6',
    glow: 'rgba(255, 77, 109, 0.2)',
    mode: 'Claro',
    verticals: ['aesthetic', 'fitness', 'wellness'],
    radius: '2rem',
    heroRadius: '2.35rem',
    cardStyle: 'glass',
    buttonStyle: 'glow',
    fontStyle: 'creator',
    sectionSpacing: 'py-24',
  },
  {
    key: 'executive-black',
    name: 'Executive Black',
    primary: '#ffffff',
    secondary: '#9ca3af',
    accent: '#3b82f6',
    background: '#0b0f19',
    surface: '#111827',
    surfaceAlt: '#1f2937',
    border: '#374151',
    text: '#f9fafb',
    textSoft: '#d1d5db',
    textMuted: '#9ca3af',
    gradientFrom: '#111827',
    gradientTo: '#0b0f19',
    glow: 'rgba(59, 130, 246, 0.15)',
    mode: 'Escuro',
    verticals: ['legal', 'consulting', 'finance'],
    radius: '1.35rem',
    heroRadius: '1.75rem',
    cardStyle: 'dark',
    buttonStyle: 'outline',
    fontStyle: 'executive',
    sectionSpacing: 'py-24',
  },
];

export const themeTokens = rawThemeTokens.map(normalizeThemeToken);

export function getTheme(themeKey, fallbackKey = 'clean-blue') {
  return themeTokens.find((theme) => theme.key === themeKey)
    || themeTokens.find((theme) => theme.key === fallbackKey)
    || themeTokens[0];
}

export function getThemeByVertical(vertical) {
  return themeTokens.find((theme) => theme.verticals.includes(vertical)) || themeTokens[0];
}

export function themeToCssVars(theme) {
  return {
    '--preview-bg': theme.background,
    '--preview-section': theme.section,
    '--preview-surface': theme.surface,
    '--preview-card': theme.surfaceAlt,
    '--preview-text': theme.text,
    '--preview-text-soft': theme.textSoft,
    '--preview-muted': theme.textMuted,
    '--preview-border': theme.border,
    '--preview-primary': theme.primary,
    '--preview-secondary': theme.secondary,
    '--preview-accent': theme.accent,
    '--preview-gradient-from': theme.gradientFrom,
    '--preview-gradient-to': theme.gradientTo,
    '--preview-radius': theme.radius,
    '--preview-hero-radius': theme.heroRadius,
    '--preview-shadow': theme.shadow,
    '--preview-glow': theme.glow,
    '--preview-hero-overlay': theme.heroOverlay,
    '--preview-fallback': theme.fallback,
    '--preview-section-spacing': theme.sectionSpacing,
  };
}

export function cardClass(theme, extra = '') {
  const base = {
    glass: 'border border-white/70 bg-white/85 backdrop-blur-xl',
    luxury: 'border border-[var(--preview-border)] bg-[var(--preview-surface)]/95',
    solid: 'border border-[var(--preview-border)] bg-[var(--preview-card)]',
    dark: 'border border-[var(--preview-border)] bg-[var(--preview-card)]',
    'glass-dark': 'border border-white/10 bg-white/10 backdrop-blur-xl',
  }[theme.cardStyle] || 'border border-[var(--preview-border)] bg-[var(--preview-card)]';

  return `${base} ${extra}`.trim();
}

export function buttonClass(theme, extra = '') {
  const base = {
    glow: 'text-white shadow-[var(--preview-glow)] hover:-translate-y-1',
    soft: 'text-white shadow-[var(--preview-glow)] hover:-translate-y-1',
    pill: 'text-white shadow-[var(--preview-glow)] hover:-translate-y-1',
    outline: 'border border-[var(--preview-border)] bg-[var(--preview-surface)] text-[var(--preview-text)] hover:-translate-y-1',
  }[theme.buttonStyle] || 'text-white shadow-[var(--preview-glow)] hover:-translate-y-1';

  return `pill-button ${base} ${extra}`.trim();
}

function normalizeThemeToken(theme) {
  const section = theme.section || theme.surface;
  const glow = normalizeGlow(theme.glow);

  return {
    ...theme,
    glow,
    section,
    mutedText: theme.textMuted,
    shadow: theme.shadow || glow,
    heroOverlay: theme.heroOverlay || buildHeroOverlay(theme.background),
    fallback: theme.fallback || buildFallback(theme),
  };
}

function normalizeGlow(glow) {
  if (!glow) return '0 22px 60px rgba(0, 0, 0, 0.16)';
  return /^rgba?\(/i.test(glow) ? `0 22px 60px ${glow}` : glow;
}

function buildHeroOverlay(background) {
  return `linear-gradient(90deg, ${withAlpha(background, 'fb')} 0%, ${withAlpha(background, 'ed')} 30%, ${withAlpha(background, '99')} 52%, ${withAlpha(background, '12')} 82%)`;
}

function buildFallback(theme) {
  return `radial-gradient(circle at 74% 28%, ${withAlpha(theme.accent, '45')} 0, transparent 34%), linear-gradient(135deg, ${theme.gradientFrom} 0%, ${theme.background} 48%, ${theme.gradientTo} 100%)`;
}

function withAlpha(color, alpha) {
  return /^#[0-9a-f]{6}$/i.test(color) ? `${color}${alpha}` : color;
}
